// <auto-generated />
namespace DiscussionApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class UpdatedMatchupinSportclasstocombineHomeandAwayteamsintostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatedMatchupinSportclasstocombineHomeandAwayteamsintostring));
        
        string IMigrationMetadata.Id
        {
            get { return "201905260135201_Updated Matchup in Sport class to combine Home and Away teams into string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
